Update jenkins-ubuntu

diff --git a/jenkins-ubuntu b/jenkins-ubuntu
--- a/jenkins-ubuntu
+++ b/jenkins-ubuntu
@@ -66,36 +66,35 @@ pipeline {
                 }
             }
         }
-        stage('Update Deployment File') {
-            steps {
-                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
-                    script {
-                        try {
-                            sh '''
-                                  set -e
-                                cd ~
-                                pwd
-                                rm -rf ${GIT_REPO_NAME}
-                                git clone https://github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git
-                                cd ${GIT_REPO_NAME}
-                                # Update the deployment file
-                                sed 's|image: dafik15/aws-inventory-project-app-14-aug:.*|image: dafik15/aws-inventory-project-app-14-aug:${BUILD_NUMBER}|g' K8S/deployment.yml
-                                git config user.email "g.dafik15@gmail.com"
-                                git config user.name "Dafik-G-2"
-                                git add K8S/deployment.yml
-                                git commit -m "Update deployment file with image version ${BUILD_NUMBER}"
-                                # git push https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
-                                # git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
-                                ls -lrt
-                                git push origin main
-                            '''
-                        } catch (Exception e) {
-                            echo "Error occurred during deployment file update: ${e.getMessage()}"
-                            throw e
-                        }
-                    }
+stage('Update Deployment File') {
+    steps {
+        withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
+            script {
+                try {
+                    sh '''
+                        set -e
+                        cd ~
+                        pwd
+                        rm -rf ${GIT_REPO_NAME}
+                        git clone https://github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git
+                        cd ${GIT_REPO_NAME}
+                        # Update the deployment file
+                        sed -i 's|image: dafik15/aws-inventory-project-app-14-aug:.*|image: dafik15/aws-inventory-project-app-14-aug:${BUILD_NUMBER}|g' K8S/deployment.yml
+                        git config user.email "g.dafik15@gmail.com"
+                        git config user.name "Dafik-G-2"
+                        git add K8S/deployment.yml
+                        git commit -m "Update deployment file with image version ${BUILD_NUMBER}"
+                        # Ensure the remote name and branch are correct
+                        git push origin main
+                    '''
+                } catch (Exception e) {
+                    echo "Error occurred during deployment file update: ${e.getMessage()}"
+                    throw e
                 }
             }
         }
+    }
+}
+
     }
 }
